### PR TITLE
Add expand option

### LINKED ISSUE #103: "Read more" button on postlist
A list of posts can be displayed on any page using the directive ``postlist``. However, I found out that some users just read the excerpt without noticing they should click on the title to read the full post.

I propose adding an option to the directive (e.g. ``:expand: "Read more..."``) to show an optional call to action to continue reading the post.

The link could look like this:

image

### PR DESCRIPTION
**Pull request by dgarcia360**
Design proposal for https://github.com/sunpy/ablog/issues/103

Fixes #103

### CODE REVIEW

**Comment by nabobalis** [comment]
Thanks for this, it looks good to me.

**Review by nabobalis — APPROVED** [review]

**Comment by nabobalis** [comment]
Did you have anything else you want to do or suggest? Otherwise I am happy to merge this.

**Comment by dgarcia360** [comment]
Thanks for the quick review! Nothing else right now. I'll check the open issues and see if I can contribute to some of them as time allows.

**Comment by nabobalis** [comment]
I will get this out in a release in next few hours.

**Pull request merged**
