### PR TITLE
metadata for parallel_read_safe

### PR DESCRIPTION
**Pull request by nabobalis**
Fixes https://github.com/sunpy/ablog/issues/264 maybe

### CODE REVIEW

**Comment by plaindocs** [comment]
Would love to get this merged in. Can I help?

**Comment by nabobalis** [comment]
Hello @plaindocs. I just forgot completely about this. Let me rebase this and get it merged and released.

**Comment by nabobalis** [comment]
This PR went a wild goose chance. 

It has been tagged for a release.

**Comment by plaindocs** [comment]
It really did! :grin: Thanks for pushing this over the line <3

**Pull request merged**
