### PR TITLE
Make pip actually use v0.9.0 instead of the version on PyPI

### PR DESCRIPTION
**Pull request by timcera**
Until the version on PyPI is updated, this "pip" command line will install v0.9.0.

### CODE REVIEW

**Comment by nabobalis** [comment]
I thought I uploaded it to PyPi yesterday. Let me check.

**Comment by markuszoeller** [comment]
Version 0.9.0 is already on pypi: https://pypi.python.org/pypi/ablog/0.9.0 It hit my setup yesterday, as I didn't pin the versions. IOW, I think this PR is not needed anymore.

**Comment by markuszoeller** [comment]
Before I forget it, thanks for continuing the effort on this package!

**Comment by nabobalis** [comment]
I would thank the people who sent in the PRs to the original repo! All I did was package and update the CI!

**Pull request closed without merging**
